//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

using LinqToDB;

namespace DataModels
{
	public interface ILogsDB : IDataContext
	{
		ITable<Log> Logs { get; }
		ITable<Push> Pushes { get; }
	}
}